COPY common_allegation (id,
    record_id,
    crid,
    officer_id,
    cat_id,
    recc_finding,
    recc_outcome,
    final_finding,
    final_outcome,
    beat,
    location,
    add1,
    add2,
    city,
    incident_date,
    start_date,
    end_date,
    investigator) FROM '/Users/eastagile/code/CPDB/data.csv' (DELIMITER ',', QUOTE '"', FORMAT 'csv');


